name: Commands Set 1 -- Shell Commands
on: [push]
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: intro message
        run: echo "Checking tools version"
      - name: multi-line check
        run: |
          node -v 
          npm -v 
      - name: Processor check using python
        run: |
          import platform
          print(platform.processor())
        shell: python
  
  directory-check:
    runs-on: windows-latest
    needs: ['check-version']
    steps:
      - name: PWD using default Powershell
        run: Get-Location
      - name: PWD using bash on windows-latest
        run: PWD
        shell: bash
