name: Commands Set 1 -- Shell Commands
on: [push]
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: intro message
        run: echo "Checking tools version"
      - name: multi-line check
        run: |
          node -v 
          npm -v 
      - name: Processor check using python
        run: |
          import platform
          print(platform.processor())
        shell: python
